export const codes = [
    { value: "0", label: "+91" },
    { value: "1", label: "+34" },
    { value: "2", label: "+76" },
    { value: "3", label: "+76" },
    { value: "4", label: "+56" },
    { value: "5", label: "+94" },
    { value: "6", label: "8332" },
    { value: "7", label: "212" },
    { value: "8", label: "09" },
    { value: "9", label: "97" },
    { value: "10", label: "10" },
    { value: "11", label: "07" },
    { value: "12", label: "36" },
];

export const brands = [
    "Brand 1", "Brand 2", "Brand 3", "Brand 4", "Brand 5",
    "Brand 6", "Brand 7", "Brand 8", "Brand 9", "Brand 10",
    "Brand 11", "Brand 12", "Brand 13", "Brand 14", "Brand 15",
];

export const categories = [
    { id: "1", name: "Trader / Wholesaler (No document required)" },
    { id: "2", name: "Authorized Dealer / Distributor (Attach brand certificate)" },
    { id: "3", name: "Brand owner (Attach brand ownership / trademark certificate)" },
];



// export const mockApiResponse = [
//     {
//         image: "https://placehold.co/50",
//         categoryL1: "Electronics",
//         categoryL2: "Mobile Phones",
//         categoryL3: "Smartphones",
//         listingName: "iPhone 14 Pro",
//         skuName: "IPH14PRO-256GB",
//         qtyStock: 25,
//         pricePerUnit: 129999,
//         listingID: "LST-001",
//         skuID: "SKU-001",
//         gstRate: 18,
//         gstAmount: 65434,
//         hsnCode: "HSN-8517",
//     },
//     {
//         image: "https://placehold.co/50",
//         categoryL1: "Electronics",
//         categoryL2: "Laptops",
//         categoryL3: "Gaming Laptops",
//         listingName: "ASUS ROG Strix",
//         skuName: "ROG-RTX4060",
//         qtyStock: 10,
//         pricePerUnit: 179999,
//         listingID: "LST-002",
//         skuID: "SKU-002",
//         gstRate: 18,
//         gstAmount: 65499,
//         hsnCode: "HSN-8471",
//     },
//     {
//         image: "https://placehold.co/51",
//         categoryL1: "Home Appliances",
//         categoryL2: "Kitchen",
//         categoryL3: "Microwaves",
//         listingName: "Samsung Convection Oven",
//         skuName: "SAM-OVN30L",
//         qtyStock: 15,
//         pricePerUnit: 29999,
//         listingID: "LST-003",
//         skuID: "SKU-003",
//         gstRate: 12,
//         gstAmount: 12434,
//         hsnCode: "HSN-8516",
//     },
//     {
//         image: "https://placehold.co/52",
//         categoryL1: "Electrical",
//         categoryL2: "Wire & Cables",
//         categoryL3: "D-Wire",
//         listingName: "Red Wire",
//         skuName: "RE-OVN30L",
//         qtyStock: 15,
//         pricePerUnit: 29999,
//         listingID: "LST-004",
//         skuID: "SKU-004",
//         gstRate: 12,
//         gstAmount: 12434,
//         hsnCode: "HSN-8516",
//     },
//     {
//         image: "https://placehold.co/53",
//         categoryL1: "Electronics",
//         categoryL2: "Tablets",
//         categoryL3: "Android Tablets",
//         listingName: "Samsung Galaxy Tab S8",
//         skuName: "SAM-TABS8",
//         qtyStock: 20,
//         pricePerUnit: 69999,
//         listingID: "LST-005",
//         skuID: "SKU-005",
//         gstRate: 18,
//         gstAmount: 22999,
//         hsnCode: "HSN-8471",
//     },
//     {
//         image: "https://placehold.co/54",
//         categoryL1: "Electronics",
//         categoryL2: "Headphones",
//         categoryL3: "Wireless",
//         listingName: "Sony WH-1000XM5",
//         skuName: "SONY-WH1000XM5",
//         qtyStock: 12,
//         pricePerUnit: 29999,
//         listingID: "LST-006",
//         skuID: "SKU-006",
//         gstRate: 18,
//         gstAmount: 5400,
//         hsnCode: "HSN-8518",
//     },
//     {
//         image: "https://placehold.co/55",
//         categoryL1: "Home Appliances",
//         categoryL2: "Cooling",
//         categoryL3: "Air Conditioners",
//         listingName: "LG Dual Inverter AC",
//         skuName: "LG-AC1.5T",
//         qtyStock: 8,
//         pricePerUnit: 45999,
//         listingID: "LST-007",
//         skuID: "SKU-007",
//         gstRate: 18,
//         gstAmount: 8299,
//         hsnCode: "HSN-8415",
//     },
//     {
//         image: "https://placehold.co/56",
//         categoryL1: "Home Appliances",
//         categoryL2: "Washing Machines",
//         categoryL3: "Front Load",
//         listingName: "Bosch 7kg Front Load",
//         skuName: "BOSCH-WM7KG",
//         qtyStock: 6,
//         pricePerUnit: 39999,
//         listingID: "LST-008",
//         skuID: "SKU-008",
//         gstRate: 12,
//         gstAmount: 4800,
//         hsnCode: "HSN-8450",
//     },
//     {
//         image: "https://placehold.co/57",
//         categoryL1: "Electronics",
//         categoryL2: "Gaming Consoles",
//         categoryL3: "PlayStation",
//         listingName: "Sony PlayStation 5",
//         skuName: "PS5-DISC",
//         qtyStock: 5,
//         pricePerUnit: 49999,
//         listingID: "LST-009",
//         skuID: "SKU-009",
//         gstRate: 18,
//         gstAmount: 8999,
//         hsnCode: "HSN-9504",
//     },
//     {
//         image: "https://placehold.co/58",
//         categoryL1: "Electronics",
//         categoryL2: "Smartwatches",
//         categoryL3: "Wearables",
//         listingName: "Apple Watch Series 9",
//         skuName: "AW-SERIES9",
//         qtyStock: 18,
//         pricePerUnit: 59999,
//         listingID: "LST-010",
//         skuID: "SKU-010",
//         gstRate: 18,
//         gstAmount: 10799,
//         hsnCode: "HSN-8517",
//     },
//     {
//         image: "https://placehold.co/59",
//         categoryL1: "Furniture",
//         categoryL2: "Living Room",
//         categoryL3: "Sofas",
//         listingName: "Leather Sofa Set",
//         skuName: "LS-SET-BRN",
//         qtyStock: 10,
//         pricePerUnit: 74999,
//         listingID: "LST-011",
//         skuID: "SKU-011",
//         gstRate: 12,
//         gstAmount: 8999,
//         hsnCode: "HSN-9401",
//     },
//     {
//         image: "https://placehold.co/60",
//         categoryL1: "Electronics",
//         categoryL2: "Televisions",
//         categoryL3: "LED TVs",
//         listingName: "Samsung 55-inch 4K TV",
//         skuName: "SAMSUNG-55-4K",
//         qtyStock: 15,
//         pricePerUnit: 85999,
//         listingID: "LST-012",
//         skuID: "SKU-012",
//         gstRate: 18,
//         gstAmount: 15479,
//         hsnCode: "HSN-8528",
//     },
//     {
//         image: "https://placehold.co/61",
//         categoryL1: "Home Appliances",
//         categoryL2: "Refrigerators",
//         categoryL3: "Double Door",
//         listingName: "Whirlpool 340L Fridge",
//         skuName: "WHIRL-340L-DD",
//         qtyStock: 7,
//         pricePerUnit: 49999,
//         listingID: "LST-013",
//         skuID: "SKU-013",
//         gstRate: 12,
//         gstAmount: 6000,
//         hsnCode: "HSN-8418",
//     },
//     {
//         image: "https://placehold.co/62",
//         categoryL1: "Kitchen Appliances",
//         categoryL2: "Cookware",
//         categoryL3: "Induction Cooktops",
//         listingName: "Prestige Induction Cooker",
//         skuName: "PRESTIGE-IC1800",
//         qtyStock: 30,
//         pricePerUnit: 4999,
//         listingID: "LST-014",
//         skuID: "SKU-014",
//         gstRate: 12,
//         gstAmount: 599,
//         hsnCode: "HSN-8516",
//     },
//     {
//         image: "https://placehold.co/49",
//         categoryL1: "Electronics",
//         categoryL2: "Mobile Phones",
//         categoryL3: "Smartphones",
//         listingName: "iPhone 14 Pro",
//         skuName: "IPH14PRO-256GB",
//         qtyStock: 25,
//         pricePerUnit: 129999,
//         listingID: "LST-001",
//         skuID: "SKU-001",
//         gstRate: 18,
//         gstAmount: 65434,
//         hsnCode: "HSN-8517",
//     },
//     {
//         image: "https://placehold.co/50",
//         categoryL1: "Electronics",
//         categoryL2: "Laptops",
//         categoryL3: "Gaming Laptops",
//         listingName: "ASUS ROG Strix",
//         skuName: "ROG-RTX4060",
//         qtyStock: 10,
//         pricePerUnit: 179999,
//         listingID: "LST-002",
//         skuID: "SKU-002",
//         gstRate: 18,
//         gstAmount: 65499,
//         hsnCode: "HSN-8471",
//     },
//     {
//         image: "https://placehold.co/51",
//         categoryL1: "Home Appliances",
//         categoryL2: "Kitchen",
//         categoryL3: "Microwaves",
//         listingName: "Samsung Convection Oven",
//         skuName: "SAM-OVN30L",
//         qtyStock: 15,
//         pricePerUnit: 29999,
//         listingID: "LST-003",
//         skuID: "SKU-003",
//         gstRate: 12,
//         gstAmount: 12434,
//         hsnCode: "HSN-8516",
//     },
//     {
//         image: "https://placehold.co/52",
//         categoryL1: "electrical",
//         categoryL2: "wire & cables",
//         categoryL3: "d-wire",
//         listingName: "red wire",
//         skuName: "RE-OVN30L",
//         qtyStock: 15,
//         pricePerUnit: 29999,
//         listingID: "LST-003",
//         skuID: "SKU-003",
//         gstRate: 12,
//         gstAmount: 12434,
//         hsnCode: "HSN-8516",
//     },
//     {
//         image: "https://placehold.co/49",
//         categoryL1: "Electronics",
//         categoryL2: "Mobile Phones",
//         categoryL3: "Smartphones",
//         listingName: "iPhone 14 Pro",
//         skuName: "IPH14PRO-256GB",
//         qtyStock: 25,
//         pricePerUnit: 129999,
//         listingID: "LST-001",
//         skuID: "SKU-001",
//         gstRate: 18,
//         gstAmount: 65434,
//         hsnCode: "HSN-8517",
//     },
//     {
//         image: "https://placehold.co/50",
//         categoryL1: "Electronics",
//         categoryL2: "Laptops",
//         categoryL3: "Gaming Laptops",
//         listingName: "ASUS ROG Strix",
//         skuName: "ROG-RTX4060",
//         qtyStock: 10,
//         pricePerUnit: 179999,
//         listingID: "LST-002",
//         skuID: "SKU-002",
//         gstRate: 18,
//         gstAmount: 65499,
//         hsnCode: "HSN-8471",
//     },
//     {
//         image: "https://placehold.co/51",
//         categoryL1: "Home Appliances",
//         categoryL2: "Kitchen",
//         categoryL3: "Microwaves",
//         listingName: "Samsung Convection Oven",
//         skuName: "SAM-OVN30L",
//         qtyStock: 15,
//         pricePerUnit: 29999,
//         listingID: "LST-003",
//         skuID: "SKU-003",
//         gstRate: 12,
//         gstAmount: 12434,
//         hsnCode: "HSN-8516",
//     },
//     {
//         image: "https://placehold.co/52",
//         categoryL1: "Electrical",
//         categoryL2: "Wire & Cables",
//         categoryL3: "D-Wire",
//         listingName: "Red Wire",
//         skuName: "RE-OVN30L",
//         qtyStock: 15,
//         pricePerUnit: 29999,
//         listingID: "LST-004",
//         skuID: "SKU-004",
//         gstRate: 12,
//         gstAmount: 12434,
//         hsnCode: "HSN-8516",
//     },
//     {
//         image: "https://placehold.co/53",
//         categoryL1: "Electronics",
//         categoryL2: "Tablets",
//         categoryL3: "Android Tablets",
//         listingName: "Samsung Galaxy Tab S8",
//         skuName: "SAM-TABS8",
//         qtyStock: 20,
//         pricePerUnit: 69999,
//         listingID: "LST-005",
//         skuID: "SKU-005",
//         gstRate: 18,
//         gstAmount: 22999,
//         hsnCode: "HSN-8471",
//     },
//     {
//         image: "https://placehold.co/54",
//         categoryL1: "Electronics",
//         categoryL2: "Headphones",
//         categoryL3: "Wireless",
//         listingName: "Sony WH-1000XM5",
//         skuName: "SONY-WH1000XM5",
//         qtyStock: 12,
//         pricePerUnit: 29999,
//         listingID: "LST-006",
//         skuID: "SKU-006",
//         gstRate: 18,
//         gstAmount: 5400,
//         hsnCode: "HSN-8518",
//     },
//     {
//         image: "https://placehold.co/55",
//         categoryL1: "Home Appliances",
//         categoryL2: "Cooling",
//         categoryL3: "Air Conditioners",
//         listingName: "LG Dual Inverter AC",
//         skuName: "LG-AC1.5T",
//         qtyStock: 8,
//         pricePerUnit: 45999,
//         listingID: "LST-007",
//         skuID: "SKU-007",
//         gstRate: 18,
//         gstAmount: 8299,
//         hsnCode: "HSN-8415",
//     },
//     {
//         image: "https://placehold.co/56",
//         categoryL1: "Home Appliances",
//         categoryL2: "Washing Machines",
//         categoryL3: "Front Load",
//         listingName: "Bosch 7kg Front Load",
//         skuName: "BOSCH-WM7KG",
//         qtyStock: 6,
//         pricePerUnit: 39999,
//         listingID: "LST-008",
//         skuID: "SKU-008",
//         gstRate: 12,
//         gstAmount: 4800,
//         hsnCode: "HSN-8450",
//     },
//     {
//         image: "https://placehold.co/57",
//         categoryL1: "Electronics",
//         categoryL2: "Gaming Consoles",
//         categoryL3: "PlayStation",
//         listingName: "Sony PlayStation 5",
//         skuName: "PS5-DISC",
//         qtyStock: 5,
//         pricePerUnit: 49999,
//         listingID: "LST-009",
//         skuID: "SKU-009",
//         gstRate: 18,
//         gstAmount: 8999,
//         hsnCode: "HSN-9504",
//     },
//     {
//         image: "https://placehold.co/58",
//         categoryL1: "Electronics",
//         categoryL2: "Smartwatches",
//         categoryL3: "Wearables",
//         listingName: "Apple Watch Series 9",
//         skuName: "AW-SERIES9",
//         qtyStock: 18,
//         pricePerUnit: 59999,
//         listingID: "LST-010",
//         skuID: "SKU-010",
//         gstRate: 18,
//         gstAmount: 10799,
//         hsnCode: "HSN-8517",
//     },
// ];



export const mockApiResponse = [
    {
        image: "https://placehold.co/50",
        listingName: "iPhone 14 Pro",
        childSku: "IPH14PRO-256GB",
        listingId: "LST-001",
        skuId: "SKU-001",
        listingUnitQty: 25,
        hsnCode: "HSN-8517",
        qtyInStock: 25,
        unitPriceWithoutGst: 129999,
        gstRate: 18,
        gstAmount: (129999 * 18) / 100,
        unitPriceIncludingGst: 129999 + (129999 * 18) / 100,
    },
    {
        image: "https://placehold.co/50",
        listingName: "ASUS ROG Strix",
        childSku: "ROG-RTX4060",
        listingId: "LST-002",
        skuId: "SKU-002",
        listingUnitQty: 10,
        hsnCode: "HSN-8471",
        qtyInStock: 10,
        unitPriceWithoutGst: 179999,
        gstRate: 18,
        gstAmount: (179999 * 18) / 100,
        unitPriceIncludingGst: 179999 + (179999 * 18) / 100,
    },
    {
        image: "https://placehold.co/51",
        listingName: "Samsung Convection Oven",
        childSku: "SAM-OVN30L",
        listingId: "LST-003",
        skuId: "SKU-003",
        listingUnitQty: 15,
        hsnCode: "HSN-8516",
        qtyInStock: 15,
        unitPriceWithoutGst: 29999,
        gstRate: 12,
        gstAmount: (29999 * 12) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 12) / 100,
    },
    {
        image: "https://placehold.co/52",
        listingName: "Red Wire",
        childSku: "RE-OVN30L",
        listingId: "LST-004",
        skuId: "SKU-004",
        listingUnitQty: 15,
        hsnCode: "HSN-8516",
        qtyInStock: 15,
        unitPriceWithoutGst: 29999,
        gstRate: 12,
        gstAmount: (29999 * 12) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 12) / 100,
    },
    {
        image: "https://placehold.co/53",
        listingName: "Samsung Galaxy Tab S8",
        childSku: "SAM-TABS8",
        listingId: "LST-005",
        skuId: "SKU-005",
        listingUnitQty: 20,
        hsnCode: "HSN-8471",
        qtyInStock: 20,
        unitPriceWithoutGst: 69999,
        gstRate: 18,
        gstAmount: (69999 * 18) / 100,
        unitPriceIncludingGst: 69999 + (69999 * 18) / 100,
    },
    {
        image: "https://placehold.co/54",
        listingName: "Sony WH-1000XM5",
        childSku: "SONY-WH1000XM5",
        listingId: "LST-006",
        skuId: "SKU-006",
        listingUnitQty: 12,
        hsnCode: "HSN-8518",
        qtyInStock: 12,
        unitPriceWithoutGst: 29999,
        gstRate: 18,
        gstAmount: (29999 * 18) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 18) / 100,
    },
    {
        image: "https://placehold.co/55",
        listingName: "LG Dual Inverter AC",
        childSku: "LG-AC1.5T",
        listingId: "LST-007",
        skuId: "SKU-007",
        listingUnitQty: 8,
        hsnCode: "HSN-8415",
        qtyInStock: 8,
        unitPriceWithoutGst: 45999,
        gstRate: 18,
        gstAmount: (45999 * 18) / 100,
        unitPriceIncludingGst: 45999 + (45999 * 18) / 100,
    },
    {
        image: "https://placehold.co/56",
        listingName: "Bosch 7kg Front Load",
        childSku: "BOSCH-WM7KG",
        listingId: "LST-008",
        skuId: "SKU-008",
        listingUnitQty: 6,
        hsnCode: "HSN-8450",
        qtyInStock: 6,
        unitPriceWithoutGst: 39999,
        gstRate: 12,
        gstAmount: (39999 * 12) / 100,
        unitPriceIncludingGst: 39999 + (39999 * 12) / 100,
    },
    {
        image: "https://placehold.co/57",
        listingName: "Sony PlayStation 5",
        childSku: "PS5-DISC",
        listingId: "LST-009",
        skuId: "SKU-009",
        listingUnitQty: 5,
        hsnCode: "HSN-9504",
        qtyInStock: 5,
        unitPriceWithoutGst: 49999,
        gstRate: 18,
        gstAmount: (49999 * 18) / 100,
        unitPriceIncludingGst: 49999 + (49999 * 18) / 100,
    },
    {
        image: "https://placehold.co/58",
        listingName: "Apple Watch Series 9",
        childSku: "AW-SERIES9",
        listingId: "LST-010",
        skuId: "SKU-010",
        listingUnitQty: 18,
        hsnCode: "HSN-8517",
        qtyInStock: 18,
        unitPriceWithoutGst: 59999,
        gstRate: 18,
        gstAmount: (59999 * 18) / 100,
        unitPriceIncludingGst: 59999 + (59999 * 18) / 100,
    },
    {
        image: "https://placehold.co/59",
        listingName: "Leather Sofa Set",
        childSku: "LS-SET-BRN",
        listingId: "LST-011",
        skuId: "SKU-011",
        listingUnitQty: 10,
        hsnCode: "HSN-9401",
        qtyInStock: 10,
        unitPriceWithoutGst: 74999,
        gstRate: 12,
        gstAmount: (74999 * 12) / 100,
        unitPriceIncludingGst: 74999 + (74999 * 12) / 100,
    },
    {
        image: "https://placehold.co/60",
        listingName: "Samsung 55-inch 4K TV",
        childSku: "SAMSUNG-55-4K",
        listingId: "LST-012",
        skuId: "SKU-012",
        listingUnitQty: 15,
        hsnCode: "HSN-8528",
        qtyInStock: 15,
        unitPriceWithoutGst: 85999,
        gstRate: 18,
        gstAmount: (85999 * 18) / 100,
        unitPriceIncludingGst: 85999 + (85999 * 18) / 100,
    },
    {
        image: "https://placehold.co/61",
        listingName: "Whirlpool 340L Fridge",
        childSku: "WHIRL-340L-DD",
        listingId: "LST-013",
        skuId: "SKU-013",
        listingUnitQty: 7,
        hsnCode: "HSN-8418",
        qtyInStock: 7,
        unitPriceWithoutGst: 49999,
        gstRate: 12,
        gstAmount: (49999 * 12) / 100,
        unitPriceIncludingGst: 49999 + (49999 * 12) / 100,
    },
    {
        image: "https://placehold.co/62",
        listingName: "Prestige Induction Cooker",
        childSku: "PRESTIGE-IC1800",
        listingId: "LST-014",
        skuId: "SKU-014",
        listingUnitQty: 30,
        hsnCode: "HSN-8516",
        qtyInStock: 30,
        unitPriceWithoutGst: 4999,
        gstRate: 12,
        gstAmount: (4999 * 12) / 100,
        unitPriceIncludingGst: 4999 + (4999 * 12) / 100,
    },
    {
        image: "https://placehold.co/63",
        listingName: "iPhone 14 Pro",
        childSku: "IPH14PRO-256GB",
        listingId: "LST-015",
        skuId: "SKU-015",
        listingUnitQty: 25,
        hsnCode: "HSN-8517",
        qtyInStock: 25,
        unitPriceWithoutGst: 129999,
        gstRate: 18,
        gstAmount: (129999 * 18) / 100,
        unitPriceIncludingGst: 129999 + (129999 * 18) / 100,
    },
    {
        image: "https://placehold.co/64",
        listingName: "ASUS ROG Strix",
        childSku: "ROG-RTX4060",
        listingId: "LST-016",
        skuId: "SKU-016",
        listingUnitQty: 10,
        hsnCode: "HSN-8471",
        qtyInStock: 10,
        unitPriceWithoutGst: 179999,
        gstRate: 18,
        gstAmount: (179999 * 18) / 100,
        unitPriceIncludingGst: 179999 + (179999 * 18) / 100,
    },
    {
        image: "https://placehold.co/65",
        listingName: "Samsung Convection Oven",
        childSku: "SAM-OVN30L",
        listingId: "LST-017",
        skuId: "SKU-017",
        listingUnitQty: 15,
        hsnCode: "HSN-8516",
        qtyInStock: 15,
        unitPriceWithoutGst: 29999,
        gstRate: 12,
        gstAmount: (29999 * 12) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 12) / 100,
    },
    {
        image: "https://placehold.co/66",
        listingName: "Red Wire",
        childSku: "RE-OVN30L",
        listingId: "LST-018",
        skuId: "SKU-018",
        listingUnitQty: 15,
        hsnCode: "HSN-8516",
        qtyInStock: 15,
        unitPriceWithoutGst: 29999,
        gstRate: 12,
        gstAmount: (29999 * 12) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 12) / 100,
    },
    {
        image: "https://placehold.co/67",
        listingName: "Samsung Galaxy Tab S8",
        childSku: "SAM-TABS8",
        listingId: "LST-019",
        skuId: "SKU-019",
        listingUnitQty: 20,
        hsnCode: "HSN-8471",
        qtyInStock: 20,
        unitPriceWithoutGst: 69999,
        gstRate: 18,
        gstAmount: (69999 * 18) / 100,
        unitPriceIncludingGst: 69999 + (69999 * 18) / 100,
    },
    {
        image: "https://placehold.co/68",
        listingName: "Sony WH-1000XM5",
        childSku: "SONY-WH1000XM5",
        listingId: "LST-020",
        skuId: "SKU-020",
        listingUnitQty: 12,
        hsnCode: "HSN-8518",
        qtyInStock: 12,
        unitPriceWithoutGst: 29999,
        gstRate: 18,
        gstAmount: (29999 * 18) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 18) / 100,
    },
    {
        image: "https://placehold.co/69",
        listingName: "LG Dual Inverter AC",
        childSku: "LG-AC1.5T",
        listingId: "LST-021",
        skuId: "SKU-021",
        listingUnitQty: 8,
        hsnCode: "HSN-8415",
        qtyInStock: 8,
        unitPriceWithoutGst: 45999,
        gstRate: 18,
        gstAmount: (45999 * 18) / 100,
        unitPriceIncludingGst: 45999 + (45999 * 18) / 100,
    },
    {
        image: "https://placehold.co/70",
        listingName: "Bosch 7kg Front Load",
        childSku: "BOSCH-WM7KG",
        listingId: "LST-022",
        skuId: "SKU-022",
        listingUnitQty: 6,
        hsnCode: "HSN-8450",
        qtyInStock: 6,
        unitPriceWithoutGst: 39999,
        gstRate: 12,
        gstAmount: (39999 * 12) / 100,
        unitPriceIncludingGst: 39999 + (39999 * 12) / 100,
    },
    {
        image: "https://placehold.co/71",
        listingName: "Sony PlayStation 5",
        childSku: "PS5-DISC",
        listingId: "LST-023",
        skuId: "SKU-023",
        listingUnitQty: 5,
        hsnCode: "HSN-9504",
        qtyInStock: 5,
        unitPriceWithoutGst: 49999,
        gstRate: 18,
        gstAmount: (49999 * 18) / 100,
        unitPriceIncludingGst: 49999 + (49999 * 18) / 100,
    },
    {
        image: "https://placehold.co/72",
        listingName: "Apple Watch Series 9",
        childSku: "AW-SERIES9",
        listingId: "LST-024",
        skuId: "SKU-024",
        listingUnitQty: 18,
        hsnCode: "HSN-8517",
        qtyInStock: 18,
        unitPriceWithoutGst: 59999,
        gstRate: 18,
        gstAmount: (59999 * 18) / 100,
        unitPriceIncludingGst: 59999 + (59999 * 18) / 100,
    },
    {
        image: "https://placehold.co/73",
        listingName: "Leather Sofa Set",
        childSku: "LS-SET-BRN",
        listingId: "LST-025",
        skuId: "SKU-025",
        listingUnitQty: 10,
        hsnCode: "HSN-9401",
        qtyInStock: 10,
        unitPriceWithoutGst: 74999,
        gstRate: 12,
        gstAmount: (74999 * 12) / 100,
        unitPriceIncludingGst: 74999 + (74999 * 12) / 100,
    },
    {
        image: "https://placehold.co/74",
        listingName: "Samsung 55-inch 4K TV",
        childSku: "SAMSUNG-55-4K",
        listingId: "LST-026",
        skuId: "SKU-026",
        listingUnitQty: 15,
        hsnCode: "HSN-8528",
        qtyInStock: 15,
        unitPriceWithoutGst: 85999,
        gstRate: 18,
        gstAmount: (85999 * 18) / 100,
        unitPriceIncludingGst: 85999 + (85999 * 18) / 100,
    },
    {
        image: "https://placehold.co/75",
        listingName: "Whirlpool 340L Fridge",
        childSku: "WHIRL-340L-DD",
        listingId: "LST-027",
        skuId: "SKU-027",
        listingUnitQty: 7,
        hsnCode: "HSN-8418",
        qtyInStock: 7,
        unitPriceWithoutGst: 49999,
        gstRate: 12,
        gstAmount: (49999 * 12) / 100,
        unitPriceIncludingGst: 49999 + (49999 * 12) / 100,
    },
    {
        image: "https://placehold.co/76",
        listingName: "Prestige Induction Cooker",
        childSku: "PRESTIGE-IC1800",
        listingId: "LST-028",
        skuId: "SKU-028",
        listingUnitQty: 30,
        hsnCode: "HSN-8516",
        qtyInStock: 30,
        unitPriceWithoutGst: 4999,
        gstRate: 12,
        gstAmount: (4999 * 12) / 100,
        unitPriceIncludingGst: 4999 + (4999 * 12) / 100,
    },
    {
        image: "https://placehold.co/77",
        listingName: "iPhone 14 Pro",
        childSku: "IPH14PRO-256GB",
        listingId: "LST-029",
        skuId: "SKU-029",
        listingUnitQty: 25,
        hsnCode: "HSN-8517",
        qtyInStock: 25,
        unitPriceWithoutGst: 129999,
        gstRate: 18,
        gstAmount: (129999 * 18) / 100,
        unitPriceIncludingGst: 129999 + (129999 * 18) / 100,
    },
    {
        image: "https://placehold.co/78",
        listingName: "ASUS ROG Strix",
        childSku: "ROG-RTX4060",
        listingId: "LST-030",
        skuId: "SKU-030",
        listingUnitQty: 10,
        hsnCode: "HSN-8471",
        qtyInStock: 10,
        unitPriceWithoutGst: 179999,
        gstRate: 18,
        gstAmount: (179999 * 18) / 100,
        unitPriceIncludingGst: 179999 + (179999 * 18) / 100,
    },
    {
        image: "https://placehold.co/79",
        listingName: "Samsung Convection Oven",
        childSku: "SAM-OVN30L",
        listingId: "LST-031",
        skuId: "SKU-031",
        listingUnitQty: 15,
        hsnCode: "HSN-8516",
        qtyInStock: 15,
        unitPriceWithoutGst: 29999,
        gstRate: 12,
        gstAmount: (29999 * 12) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 12) / 100,
    },
    {
        image: "https://placehold.co/80",
        listingName: "Red Wire",
        childSku: "RE-OVN30L",
        listingId: "LST-032",
        skuId: "SKU-032",
        listingUnitQty: 15,
        hsnCode: "HSN-8516",
        qtyInStock: 15,
        unitPriceWithoutGst: 29999,
        gstRate: 12,
        gstAmount: (29999 * 12) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 12) / 100,
    },
    {
        image: "https://placehold.co/81",
        listingName: "Samsung Galaxy Tab S8",
        childSku: "SAM-TABS8",
        listingId: "LST-033",
        skuId: "SKU-033",
        listingUnitQty: 20,
        hsnCode: "HSN-8471",
        qtyInStock: 20,
        unitPriceWithoutGst: 69999,
        gstRate: 18,
        gstAmount: (69999 * 18) / 100,
        unitPriceIncludingGst: 69999 + (69999 * 18) / 100,
    },
    {
        image: "https://placehold.co/82",
        listingName: "Sony WH-1000XM5",
        childSku: "SONY-WH1000XM5",
        listingId: "LST-034",
        skuId: "SKU-034",
        listingUnitQty: 12,
        hsnCode: "HSN-8518",
        qtyInStock: 12,
        unitPriceWithoutGst: 29999,
        gstRate: 18,
        gstAmount: (29999 * 18) / 100,
        unitPriceIncludingGst: 29999 + (29999 * 18) / 100,
    },
    {
        image: "https://placehold.co/83",
        listingName: "LG Dual Inverter AC",
        childSku: "LG-AC1.5T",
        listingId: "LST-035",
        skuId: "SKU-035",
        listingUnitQty: 8,
        hsnCode: "HSN-8415",
        qtyInStock: 8,
        unitPriceWithoutGst: 45999,
        gstRate: 18,
        gstAmount: (45999 * 18) / 100,
        unitPriceIncludingGst: 45999 + (45999 * 18) / 100,
    },
    {
        image: "https://placehold.co/84",
        listingName: "Bosch 7kg Front Load",
        childSku: "BOSCH-WM7KG",
        listingId: "LST-036",
        skuId: "SKU-036",
        listingUnitQty: 6,
        hsnCode: "HSN-8450",
        qtyInStock: 6,
        unitPriceWithoutGst: 39999,
        gstRate: 12,
        gstAmount: (39999 * 12) / 100,
        unitPriceIncludingGst: 39999 + (39999 * 12) / 100,
    },
    {
        image: "https://placehold.co/85",
        listingName: "Sony PlayStation 5",
        childSku: "PS5-DISC",
        listingId: "LST-037",
        skuId: "SKU-037",
        listingUnitQty: 5,
        hsnCode: "HSN-9504",
        qtyInStock: 5,
        unitPriceWithoutGst: 49999,
        gstRate: 18,
        gstAmount: (49999 * 18) / 100,
        unitPriceIncludingGst: 49999 + (49999 * 18) / 100,
    },
    {
        image: "https://placehold.co/86",
        listingName: "Apple Watch Series 9",
        childSku: "AW-SERIES9",
        listingId: "LST-038",
        skuId: "SKU-038",
        listingUnitQty: 18,
        hsnCode: "HSN-8517",
        qtyInStock: 18,
        unitPriceWithoutGst: 59999,
        gstRate: 18,
        gstAmount: (59999 * 18) / 100,
        unitPriceIncludingGst: 59999 + (59999 * 18) / 100,
    },
    {
        image: "https://placehold.co/87",
        listingName: "Leather Sofa Set",
        childSku: "LS-SET-BRN",
        listingId: "LST-039",
        skuId: "SKU-039",
        listingUnitQty: 10,
        hsnCode: "HSN-9401",
        qtyInStock: 10,
        unitPriceWithoutGst: 74999,
        gstRate: 12,
        gstAmount: (74999 * 12) / 100,
        unitPriceIncludingGst: 74999 + (74999 * 12) / 100,
    },
    {
        image: "https://placehold.co/88",
        listingName: "Samsung 55-inch 4K TV",
        childSku: "SAMSUNG-55-4K",
        listingId: "LST-040",
        skuId: "SKU-040",
        listingUnitQty: 15,
        hsnCode: "HSN-8528",
        qtyInStock: 15,
        unitPriceWithoutGst: 85999,
        gstRate: 18,
        gstAmount: (85999 * 18) / 100,
        unitPriceIncludingGst: 85999 + (85999 * 18) / 100,
    },
    {
        image: "https://placehold.co/89",
        listingName: "Whirlpool 340L Fridge",
        childSku: "WHIRL-340L-DD",
        listingId: "LST-041",
        skuId: "SKU-041",
        listingUnitQty: 7,
        hsnCode: "HSN-8418",
        qtyInStock: 7,
        unitPriceWithoutGst: 49999,
        gstRate: 12,
        gstAmount: (49999 * 12) / 100,
        unitPriceIncludingGst: 49999 + (49999 * 12) / 100,
    },
    {
        image: "https://placehold.co/90",
        listingName: "Prestige Induction Cooker",
        childSku: "PRESTIGE-IC1800",
        listingId: "LST-042",
        skuId: "SKU-042",
        listingUnitQty: 30,
        hsnCode: "HSN-8516",
        qtyInStock: 30,
        unitPriceWithoutGst: 4999,
        gstRate: 12,
        gstAmount: (4999 * 12) / 100,
        unitPriceIncludingGst: 4999 + (4999 * 12) / 100,
    },
];